variables:
  REPODEST: /home/builder/packages/${CI_COMMIT_REF_NAME}
  GIT_STRATEGY: fetch

build:
  tags:
    - alpine-sdk
  script:
    - "cd .apk/artello/gobetween"
    - "abuild checksum"
    - "abuild -r"
    - "s3cmd sync s3://artellectual.apk.build/packages/${CI_COMMIT_REF_NAME}/ /home/builder/packages/${CI_COMMIT_REF_NAME}/"
    - "abuild cleanoldpkg"
    - "s3cmd sync --delete-removed /home/builder/packages/${CI_COMMIT_REF_NAME}/ s3://artellectual.apk.build/packages/${CI_COMMIT_REF_NAME}/"