stages:
  - build

variables:
  REPODEST: /home/builder/packages/${CI_COMMIT_REF_NAME}
  PACKAGE_DEST: /home/builder/packages/${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAMESPACE}/
  S3_DEST: s3://apk.build/packages/${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAMESPACE}/
  GIT_STRATEGY: fetch

build:
  stage: build
  tags:
    - alpine-sdk
  script:
    - "rm -rf ${PACKAGE_DEST}"
    - "cd .apk/artello/gobetween"
    - "abuild checksum"
    - "abuild -r"
    - "s3cmd sync ${S3_DEST} ${PACKAGE_DEST}"
    - "abuild cleanoldpkg"
    - "s3cmd sync --delete-removed ${PACKAGE_DEST} ${S3_DEST}"