#!/bin/sh

keys="
  LXD_ADDRESS \
  LXD_REMOTE_NAME \
  LXD_REMOTE_PASSWORD \
"

for k in ${keys}; do
  export ${k}="$(curl -s --unix-socket /dev/lxd/sock x/1.0/config/user.${k})"
done

envsubst < /var/lib/gobetween/gobetween-lxd.tmpl > /var/lib/gobetween/gobetween-lxd.toml

exec /var/lib/gobetween/bin/gobetween -c /var/lib/gobetween/gobetween-lxd.toml